### ISSUE TITLE
How can i get the Openlit UI after deploy the Helm chart?

### ISSUE THREAD

**Issue by saibattula93** [openlit/helm#18]
How can i get the UI after Deploy the Openlit Helm chart? and I am getting the all pods and service are running and i am using GCP VMs and inside that VM i am install the K8S.

<img width="707" alt="image" src="https://github.com/user-attachments/assets/c4a4dfcd-2d1a-4b80-b9c1-a36d299b2d0d">

**Comment by amanagarwal042** [comment]
```
kubectl port-forward svc/openlit 3000
```

This should work (Apologies for the very very late reply, I didnt see the issues on this repo)

**Comment by andreys42** [comment]
> ```
> kubectl port-forward svc/openlit 3000
> ```
> 
> This should work (Apologies for the very very late reply, I didnt see the issues on this repo)

This is not working if your cluster is remote

**Comment by amanagarwal042** [comment]
> This is not working if your cluster is remote

You can then try setting the openlit sbc to be of type LoadBalancer and then access via the LoadBalancer address:3000

**Comment by andreys42** [comment]
> > This is not working if your cluster is remote
> 
> You can then try setting the openlit sbc to be of type LoadBalancer and then access via the LoadBalancer address:3000

I guess all of the deployed (by default) openlit `svc`'s are LoadBalander types

**Comment by amanagarwal042** [comment]
Do you have the LoadBalancer URL?
I can help you access via that

if you do `kubectl get svc` and check the External URL for openlit svc. The go to that `http://<lb-ip>:3000`

**Comment by andreys42** [comment]
> Do you have the LoadBalancer URL? I can help you access via that
> 
> if you do `kubectl get svc` and check the External URL for openlit svc. The go to that `http://<lb-ip>:3000`

I got you

The problem is that I need it to be accessible via Ingress (https://cluster_name/ingress_name), but it’s not working as expected — styles aren’t loading properly. Basepath in Node.js app need to be fixed...

**Comment by amanagarwal042** [comment]
hmm could you share logs or screenshots?

**Comment by andreys42** [comment]
> hmm could you share logs or screenshots?

Here is what I'm seeing in a browser
<img width="1011" height="592" alt="Image" src="https://github.com/user-attachments/assets/53444266-22c3-44ba-b12b-249c8d3e7325" />

Browser tries to download resources like
`https://ai-lab.rt-solar.ru/_next/static/chunks/...` 
but fails since URL should also refer to service name: 
`https://ai-lab.rt-solar.ru/**openlit**/_next/static/chunks/...`

It cannot be handled with ingress paths features

I believe problem in Next.js routing and this should be fixed with defining basePath in next.config.js, but I cannot find one in `openlit-0` cointainer, so looks like the only way is to build new one (what is quite hard for me in my environment)

**Comment by amanagarwal042** [comment]
@AmanAgarwal041 could you help in debugging this?

**Comment by AmanAgarwal041** [comment]
@andreys42 I will have a look at it

**Comment by AmanAgarwal041** [comment]
@andreys42 Are you accessing the openlit ui as `https://ai-lab.rt-solar.ru/openlit-0` instead of `https://ai-lab.rt-solar.ru/` ?

**Comment by andreys42** [comment]
> [@andreys42](https://github.com/andreys42) Are you accessing the openlit ui as `https://ai-lab.rt-solar.ru/openlit-0` instead of `https://ai-lab.rt-solar.ru/` ?


No, its ``https://ai-lab.rt-solar.ru/openlit` since my ingress configured that way:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openlit-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 16g

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai-lab.rt-solar.ru
      secretName: ailab-tls
  rules:
    - host: ai-lab.rt-solar.ru
      http:
        paths:
          - path: /openlit(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: openlit
                port:
                  number: 3000
```
