### ISSUE TITLE
GKE Ingress Health Check Fails Due to Default Path

### ISSUE THREAD

**Issue by zacchenit** [openlit/helm#19]
If I want to deploy OpenLit on GKE and expose it externally via Ingress, I encounter an issue. The default health check path for the GCP Load Balancer is `/`, and OpenLit redirects from `/` with a 307 status to another page, causing the health check to fail.

However, I can resolve this issue by setting up a GCP BackendConfig. Therefore, I would like to have the ability to add custom annotations in the `values.yaml` service configuration.

For example:

```yaml
# Kubernetes Service configuration for OpenLIT
service:
  # Custom annotations
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"openlit-backendconfig"}}'
  # Type of service (e.g., LoadBalancer, NodePort)
  type: ClusterIP
  # Port on which the service is exposed
  port: 3000
  # Session affinity configuration
  sessionAffinity: None
```

Do you have any better suggestions? Or if assistance is needed, I can try to take it up.
